name: example
description: A new Flutter project.

publish_to: "none"

version: 0.0.9+2

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vs_media_picker:
    path: ../
  provider: ^6.0.5
  photo_view: ^0.14.0
  better_video_player: ^1.2.8
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
